#!/bin/bash

echo -e "Git Script (add, commit, push) with message -> \033[1;36m"$1"\033[0;35m\n"

if [ -z "$1" ]; then
	echo -e "\033[0;31m==> No commit message supplied, exiting...\033[0m\n"
else
	read -p 'Continue? (y/n) ' yesno
	if [ $yesno = "y" ]; then
		printf "\033[0;32m==> RUNNING SCRIPT\n\033[0m"
		printf "\033[1;33m-> git add .\033[0m"
		git add .;
		printf "\033[1;33m-> git commit -m "$1"\n\033[0m"
		git commit -m "$1";
		printf "\033[1;33m-> git push -u origin master\n\033[0m"
		git push -u origin master
		fi
fi
echo -e "\033[0;32m==> Finishing script\033[0m\n"
