#!/bin/bash

echo -e "Git Script: Creating a new repository"

read -p 'Continue? (y/n) ' yesno

if [ $yesno = "y" ]; then
	printf "\033[0;32m==> RUNNING SCRIPT\n\033[0m"
	printf "\033[1;33m-> git init\n\033[0m"
	git init;
	printf "\033[1;33m-> git add .\n\033[0m"
	git add .;
	printf "\033[1;33m-> git commit -m "first commit"\n\033[0m"
	git commit -m "first commit";
fi

echo -e "\033[0;32m==> Finishing script\033[0m\n"
