#!/bin/bash

echo -e "Git Script: Upload local repository to Github.com -> \033[1;36m"$1"\033[0;35m\n"

if [ -z "$1" ]; then
	echo -e "\033[0;31m==> No github repository supplied, exiting...\033[0m\n"
else
	read -p 'Continue? (y/n) ' yesno
	if [ $yesno = "y" ]; then
		printf "\033[0;32m==> RUNNING SCRIPT\n\033[0m"
		printf "\033[1;33m-> git remote add origin $1\n\033[0m"
		git remote add origin $1;
		printf "\033[1;33m-> git pull --rebase origin master\n\033[0m"
		git pull --rebase origin master;
		printf "\033[1;33m-> git push -u origin master\n\033[0m"
		git push -u origin master
		fi
fi
echo -e "\033[0;32m==> Finishing script\033[0m\n"
